1982 Incorrect balance check when create dex order
ApolloFoundation/Apollo-web-ui pull request #105
Opened 2021-06-02 20:32 UTC by RomanFirstBridge

edit current balance check

2021-06-02 20:35 UTC, elli-kolisnichenko requested changes

2021-06-02 20:35 UTC, elli-kolisnichenko commented on src/containers/account/exchange/dashboard/trade-apollo/sell-form/index.jsx
> +          if (Number.isNaN(currentBalanceAPL) || currentBalanceAPL === 0 || currentBalanceAPL < ((offerAmount + feeATM) / 10)) {
Может тут достаточно было бы такой проверки?
`if (!currentBalanceAPL || currentBalanceAPL < ((offerAmount + feeATM) / 10)) {`

2021-06-02 21:10 UTC, RomanFirstBridge commented on src/containers/account/exchange/dashboard/trade-apollo/sell-form/index.jsx
> +          if (Number.isNaN(currentBalanceAPL) || currentBalanceAPL === 0 || currentBalanceAPL < ((offerAmount + feeATM) / 10)) {
как раз из-за этого и была ошибка, если я правильно понял. Есть момент двойственности баланса (он может прийти и из dashboardAccoountInfo.unconfirmedBalance, и из  balanceAPL). В тоже время если balanceAPL = null , но при этом мы получили его в dashboardAccoountInfo.unconfirmedBalance и соотвественно currentBalanceAPL имеет некоторое значение, то у нас выполнение кода остановится, т.к. balanceAPL = null.

при этом если мы в обоих полях ничего не получим, то currentBalanceAPL = NaN и с помощью проверки на NaN мы это вычисляем.

Я, конечно, могу ошибаться по тому как нам приходит баланс и можемт быть dashboardAccoountInfo.unconfirmedBalance и balanceAPL связаны между собой. Но при этом все-равно вариант с Number.isNan является немного более комплексным, т.к. включает в себя проверку обоих источников получения состояния баланса

2021-06-02 21:17 UTC, RomanFirstBridge commented on src/containers/account/exchange/dashboard/trade-apollo/sell-form/index.jsx
> +          if (Number.isNaN(currentBalanceAPL) || currentBalanceAPL === 0 || currentBalanceAPL < ((offerAmount + feeATM) / 10)) {
согласен, так меньше проверок и более прозрачно

2021-06-03 07:01 UTC, elli-kolisnichenko approved these changes

2021-06-03 07:01 UTC, merged