Feature/apl 1977
ApolloFoundation/Apollo-web-ui pull request #106
Opened 2021-06-03 21:12 UTC by RomanFirstBridge

2021-06-04 14:13 UTC, elli-kolisnichenko requested changes

2021-06-04 14:13 UTC, elli-kolisnichenko commented on src/containers/account/login/login-modal/forms/viaSecretPhraseForm.jsx
> +import { Switcher } from 'containers/components/form-components/switcher/switcher';
поменяй на относительный путь

2021-06-04 14:13 UTC, elli-kolisnichenko commented on src/containers/account/login/login-modal/login-accordions/standart-wallet/index.jsx
> +import { Accordion } from 'containers/components/accordion';
аналогично

2021-06-04 14:13 UTC, elli-kolisnichenko commented on src/containers/components/accordion/index.jsx
> +  }, [setIsOpen, onSelectItem]);
тут может еще надо отслеживать `id`

2021-06-07 07:08 UTC, RomanFirstBridge commented on src/containers/account/login/login-modal/forms/viaSecretPhraseForm.jsx
> +import { Switcher } from 'containers/components/form-components/switcher/switcher';
fixed

2021-06-07 07:08 UTC, RomanFirstBridge commented on src/containers/account/login/login-modal/login-accordions/standart-wallet/index.jsx
> +import { Accordion } from 'containers/components/accordion';
fixed

2021-06-07 07:08 UTC, RomanFirstBridge commented on src/containers/components/accordion/index.jsx
> +  }, [setIsOpen, onSelectItem]);
fixed

2021-06-07 07:38 UTC, elli-kolisnichenko approved these changes

2021-06-07 07:41 UTC, merged