ids has been added
ApolloFoundation/Apollo-web-ui pull request #219
Opened 2021-09-07 08:32 UTC by ArmanArman01

2021-09-07 08:44 UTC, elli-kolisnichenko requested changes

2021-09-07 08:44 UTC, elli-kolisnichenko commented on src/containers/components/button-tabs/index.jsx
>            type="button"
Странно, тут нет key. Добавь пожалуйста, пока заметили

2021-09-07 08:44 UTC, elli-kolisnichenko commented on src/containers/components/form-components/file-input.js
> +                        idForTest=""
Почему пустой атрибут? И я бы может не вводила его так, а там где используется можно указать используя id по подобию просто id={`input_${id}`}

2021-09-07 08:44 UTC, elli-kolisnichenko commented on src/containers/components/input-upload/index.js
> +          <input {...getInputProps()} accept={accept} id={idForTest}/>
смотри предыдущий комментарий

2021-09-07 10:44 UTC, elli-kolisnichenko requested changes

2021-09-07 10:44 UTC, elli-kolisnichenko commented on src/containers/components/input-upload/index.js
> +          <input {...getInputProps()} accept={accept} id={id}/>
Я имела ввиду не так, на странице не может быть два элемента с одинаковым id
id={`input_${id}`}

2021-09-07 10:45 UTC, elli-kolisnichenko commented on src/containers/components/input-upload/index.js
> +          <input {...getInputProps()} accept={accept} id={id}/>
если что можем созвониться) тут просто еще форматирование кавычки убирает

2021-09-07 11:52 UTC, elli-kolisnichenko approved these changes

2021-09-07 12:21 UTC, RomanFirstBridge commented on src/containers/account/login/create-user/forms/standardWalletForm.jsx
> +              id="submit_newUser"
посклько в целом на проекте используется camelCase или же написание через дефис, можешь, пожалуйста, поправить именование id и прочих переменных

2021-09-08 08:01 UTC, elli-kolisnichenko approved these changes

2021-09-08 08:03 UTC, elli-kolisnichenko commented on src/containers/account/login/create-user/forms/standardWalletForm.jsx
> +              id="submit_newUser"
@RomanFirstBridge Утвердили изменение по аналогии с классами - kebab-case. Берем за стандарт для всех последующих id

2021-09-08 08:05 UTC, merged